### ISSUE TITLE
dlogMh -> self.dlogMh

### ISSUE THREAD

**Issue by alexander-mead** [DarkQuestCosmology/dark_emulator_public#1]
On line 279 of `hod_interface.py`: https://github.com/DarkQuestCosmology/dark_emulator_public/blob/af71ff875d6a05462822c84cbc2a3791a8f5294b/dark_emulator/model_hod/hod_interface.py#L279

Should it read `dx=self.dlogMh` instead of `dx=dlogMh`? I'm getting an undefined variable warning flagging up on my IDE.

**Comment by HironaoMiyatake** [comment]
Thank you for catching this! In [branch #1](https://github.com/DarkQuestCosmology/dark_emulator_public/tree/%231), I've fixed that and added a method [`get_ng_cen()`](https://github.com/DarkQuestCosmology/dark_emulator_public/blob/ba5871c78ee9735bfe727f075804f19385f41540/dark_emulator/model_hod/hod_interface.py#L277), which calls necessary methods before calling [`_compute_ng_cen()`](https://github.com/DarkQuestCosmology/dark_emulator_public/blob/ba5871c78ee9735bfe727f075804f19385f41540/dark_emulator/model_hod/hod_interface.py#L1596) and returns the abundance of central galaxies. I'll make a pull request.
