### ISSUE TITLE
clustering predictions beyond redshift 1.5

### ISSUE THREAD

**Issue by JohanComparat** [DarkQuestCosmology/dark_emulator_public#17]
Hello, 

I am using this fantastic tool you have developed. Would it be possible to extended the predictions of clustering to redshift 2 or 3 ? 

Indeed ongoing spectroscopic surveys are gathering large samples there and having this tool to interpret these would be great.

Best wishes

**Comment by nishimichi** [comment]
Thanks for the inquiry. Unfortunately, the current emulator is built based on simulation data below z<1.5, and higher redshifts are not supported. We are now performing the 2nd series of simulations, and they will cover up to z~3. I expect that it will take some time, but hopefully we can make it in the near future.

**Comment by JohanComparat** [comment]
Thank you, I am looking forward to it.
