### ISSUE TITLE
cannot import name 'fftlog' when importing dark_emulator

### ISSUE THREAD

**Issue by aferte** [DarkQuestCosmology/dark_emulator_public#22]
Hi, 

I am trying to run the dark emulator using a pip installation:
> pip install dark_emulator 

was successful. 
Then running 

> from dark_emulator import darkemu

in ipython, leads to this error: 
ImportError: cannot import name 'fftlog' from partially initialized module 'dark_emulator' (most likely due to a circular import) (/Users/ferte/anaconda3/lib/python3.9/site-packages/dark_emulator/__init__.py)

Any inputs on how to solve this? 

Thank you, 
Best, 
Agnès

**Comment by HironaoMiyatake** [comment]
@git-sunao , could you please take a look at this?

**Comment by cheymans** [comment]
For anyone else stumbling across this issue, there is a happy workaround that means you can still use the most excellent dark emulator:

`pip install dark_emulator==1.0.23`

**Comment by nishimichi** [comment]
Thanks for the discussion. The problem is solved in v 1.1.2.

**Comment by cheymans** [comment]
Wonderful - many thanks :)

**Comment by cheymans** [comment]
Just to let you’ve know we’ve fun some comparison tests with the older version, and are very happy with the FFTlog speed-up with this version! Fantastic.  Thanks so much!
