### ISSUE TITLE
Turn off Colossus cache

### ISSUE THREAD

**Issue by HironaoMiyatake** [DarkQuestCosmology/dark_emulator_public#7]
We should turn off Colossus cache since it slows down model calculation when running chains. It can be done when instantiating cosmology class by putting persistence = ''.

**Comment by nishimichi** [comment]
Thank you for reporting this. OK. Could you please implement the necessary modifications and send a pull request?

**Comment by HironaoMiyatake** [comment]
I just made a PR #8. Please review it.
